/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Sport = IDL.Variant({
  'basketball' : IDL.Null,
  'other' : IDL.Text,
  'football' : IDL.Null,
  'athletics' : IDL.Null,
  'cricket' : IDL.Null,
});
export const Assessment = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'scout' : IDL.Principal,
  'sport' : Sport,
});
export const PlayerProfile = IDL.Record({
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'sport' : Sport,
  'village' : IDL.Text,
});
export const SponsorProfile = IDL.Record({
  'id' : IDL.Principal,
  'orgName' : IDL.Text,
  'description' : IDL.Text,
  'sport' : Sport,
});
export const VideoMetadata = IDL.Record({
  'id' : IDL.Principal,
  'title' : IDL.Text,
  'playerId' : IDL.Principal,
  'description' : IDL.Text,
  'sport' : Sport,
  'timestamp' : IDL.Int,
  'blobId' : IDL.Text,
});
export const AppRole = IDL.Variant({
  'player' : IDL.Null,
  'scout' : IDL.Null,
  'sponsor' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : AppRole,
  'name' : IDL.Text,
});
export const Score = IDL.Record({
  'mental' : IDL.Nat,
  'playerId' : IDL.Principal,
  'tactical' : IDL.Nat,
  'technical' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'physical' : IDL.Nat,
  'assessmentId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignScore' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'createAssessment' : IDL.Func([IDL.Text, IDL.Text, Sport, IDL.Int], [], []),
  'createOrUpdatePlayer' : IDL.Func(
      [IDL.Text, Sport, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'createSponsorProfile' : IDL.Func([IDL.Text, Sport, IDL.Text], [], []),
  'getAllAssessments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Assessment))],
      ['query'],
    ),
  'getAllPlayers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PlayerProfile))],
      ['query'],
    ),
  'getAllSponsors' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, SponsorProfile))],
      ['query'],
    ),
  'getAllVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([IDL.Opt(Sport)], [IDL.Vec(Score)], ['query']),
  'getPlayer' : IDL.Func([IDL.Principal], [IDL.Opt(PlayerProfile)], ['query']),
  'getPlayerScores' : IDL.Func([IDL.Principal], [IDL.Vec(Score)], ['query']),
  'getShortlistedPlayers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideosByPlayer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VideoMetadata)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'shortlistPlayer' : IDL.Func([IDL.Principal], [], []),
  'uploadVideo' : IDL.Func(
      [IDL.Text, IDL.Text, Sport, IDL.Text, IDL.Int],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Sport = IDL.Variant({
    'basketball' : IDL.Null,
    'other' : IDL.Text,
    'football' : IDL.Null,
    'athletics' : IDL.Null,
    'cricket' : IDL.Null,
  });
  const Assessment = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'scout' : IDL.Principal,
    'sport' : Sport,
  });
  const PlayerProfile = IDL.Record({
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'sport' : Sport,
    'village' : IDL.Text,
  });
  const SponsorProfile = IDL.Record({
    'id' : IDL.Principal,
    'orgName' : IDL.Text,
    'description' : IDL.Text,
    'sport' : Sport,
  });
  const VideoMetadata = IDL.Record({
    'id' : IDL.Principal,
    'title' : IDL.Text,
    'playerId' : IDL.Principal,
    'description' : IDL.Text,
    'sport' : Sport,
    'timestamp' : IDL.Int,
    'blobId' : IDL.Text,
  });
  const AppRole = IDL.Variant({
    'player' : IDL.Null,
    'scout' : IDL.Null,
    'sponsor' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'appRole' : AppRole, 'name' : IDL.Text });
  const Score = IDL.Record({
    'mental' : IDL.Nat,
    'playerId' : IDL.Principal,
    'tactical' : IDL.Nat,
    'technical' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'physical' : IDL.Nat,
    'assessmentId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignScore' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'createAssessment' : IDL.Func([IDL.Text, IDL.Text, Sport, IDL.Int], [], []),
    'createOrUpdatePlayer' : IDL.Func(
        [IDL.Text, Sport, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'createSponsorProfile' : IDL.Func([IDL.Text, Sport, IDL.Text], [], []),
    'getAllAssessments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Assessment))],
        ['query'],
      ),
    'getAllPlayers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PlayerProfile))],
        ['query'],
      ),
    'getAllSponsors' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, SponsorProfile))],
        ['query'],
      ),
    'getAllVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([IDL.Opt(Sport)], [IDL.Vec(Score)], ['query']),
    'getPlayer' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'getPlayerScores' : IDL.Func([IDL.Principal], [IDL.Vec(Score)], ['query']),
    'getShortlistedPlayers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideosByPlayer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VideoMetadata)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'shortlistPlayer' : IDL.Func([IDL.Principal], [], []),
    'uploadVideo' : IDL.Func(
        [IDL.Text, IDL.Text, Sport, IDL.Text, IDL.Int],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };