/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'player' : null } |
  { 'scout' : null } |
  { 'sponsor' : null };
export interface Assessment {
  'id' : string,
  'date' : bigint,
  'name' : string,
  'scout' : Principal,
  'sport' : Sport,
}
export interface PlayerProfile {
  'age' : bigint,
  'bio' : string,
  'name' : string,
  'sport' : Sport,
  'village' : string,
}
export interface Score {
  'mental' : bigint,
  'playerId' : Principal,
  'tactical' : bigint,
  'technical' : bigint,
  'totalScore' : bigint,
  'physical' : bigint,
  'assessmentId' : string,
}
export interface SponsorProfile {
  'id' : Principal,
  'orgName' : string,
  'description' : string,
  'sport' : Sport,
}
export type Sport = { 'basketball' : null } |
  { 'other' : string } |
  { 'football' : null } |
  { 'athletics' : null } |
  { 'cricket' : null };
export interface UserProfile { 'appRole' : AppRole, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoMetadata {
  'id' : Principal,
  'title' : string,
  'playerId' : Principal,
  'description' : string,
  'sport' : Sport,
  'timestamp' : bigint,
  'blobId' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignScore' : ActorMethod<
    [string, Principal, bigint, bigint, bigint, bigint],
    undefined
  >,
  'createAssessment' : ActorMethod<[string, string, Sport, bigint], undefined>,
  'createOrUpdatePlayer' : ActorMethod<
    [string, Sport, string, string, bigint],
    undefined
  >,
  'createSponsorProfile' : ActorMethod<[string, Sport, string], undefined>,
  'getAllAssessments' : ActorMethod<[], Array<[string, Assessment]>>,
  'getAllPlayers' : ActorMethod<[], Array<[Principal, PlayerProfile]>>,
  'getAllSponsors' : ActorMethod<[], Array<[Principal, SponsorProfile]>>,
  'getAllVideos' : ActorMethod<[], Array<VideoMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[[] | [Sport]], Array<Score>>,
  'getPlayer' : ActorMethod<[Principal], [] | [PlayerProfile]>,
  'getPlayerScores' : ActorMethod<[Principal], Array<Score>>,
  'getShortlistedPlayers' : ActorMethod<[Principal], Array<Principal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideosByPlayer' : ActorMethod<[Principal], Array<VideoMetadata>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'shortlistPlayer' : ActorMethod<[Principal], undefined>,
  'uploadVideo' : ActorMethod<
    [string, string, Sport, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];